"""Order table

Revision ID: 08515c710c08
Revises: 92129620a3e1
Create Date: 2023-08-06 12:59:32.968086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08515c710c08'
down_revision = '92129620a3e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('pincode',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('pincode',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
