"""remove mobile_no and email

Revision ID: 9e29f4444832
Revises: e1f312d3e5f3
Create Date: 2023-08-13 12:15:22.913156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e29f4444832'
down_revision = 'e1f312d3e5f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('mobile_number')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=500), nullable=False))
        batch_op.add_column(sa.Column('mobile_number', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
